apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gfttechnicaltestapplication 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gfttechnicaltestapplication 
    spec:
      containers:
        - name: gfttechnicaltestapplication 
          image: arielmoraesacr.azurecr.io/gfttechnicaltestapplication
          ports:
          - containerPort: 80