apiVersion: v1
kind: Service
metadata:
    name: gfttechnicaltestapplication
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    loadBalancerIP: 10.0.2.36
    ports:
    - port: 80 
    selector:
        app: gfttechnicaltestapplication